root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project: true

settings:
  import/resolver:
    typescript: true
    node: true

ignorePatterns:
  - 'build'
  - 'vitest.config.ts'

plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'import'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended-type-checked'
  - 'plugin:@typescript-eslint/stylistic-type-checked'
  - 'plugin:@typescript-eslint/strict-type-checked'
  - 'standard-with-typescript'
  - 'plugin:promise/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:n/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:jsdoc/recommended-typescript-error'
  - 'plugin:vitest/all'

rules:
  '@typescript-eslint/consistent-type-definitions': ['error', 'type']
  '@typescript-eslint/non-nullable-type-assertion-style': 'off'
  '@typescript-eslint/promise-function-async': 'off'
  '@typescript-eslint/strict-boolean-expressions': ['error', allowNullableObject: true]
  # covered by import/no-extraneous-dependencies
  'n/no-extraneous-import': 'off'
  'import/no-default-export': 'error'
  # disabled since it's already covered by the 'import/no-unresolved'
  'n/no-missing-import': 'off'
  'import/no-unresolved': 'error'
  'jsdoc/check-param-names': ['error', checkDestructured: false]
  'jsdoc/require-hyphen-before-param-description': 'error'
  'jsdoc/require-jsdoc': ['error', { 'require': { 'FunctionExpression': true, 'ArrowFunctionExpression': true } }]
  'jsdoc/require-param': ['error', checkDestructured: false]
  'jsdoc/require-returns': 'off'
  'jsdoc/require-throws': 'error'
  'jsdoc/tag-lines': ['error', 'any', startLines: 1]
