parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'

ignorePatterns:
  - 'build'
  - 'vitest.config.ts'

plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'import'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:@typescript-eslint/strict'
  - 'standard-with-typescript'
  - 'plugin:promise/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:n/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:jsdoc/recommended-typescript-error'
  - 'plugin:vitest/all'

settings:
  import/resolver:
    typescript: true
    node: true

rules:
  '@typescript-eslint/consistent-type-definitions': ['error', 'type']
  '@typescript-eslint/promise-function-async': 'off'
  'import/no-default-export': 'error'
  'import/no-unresolved': 'error'
  # disabled since it's already covered by the 'import/no-unresolved'
  'n/no-missing-import': 'off'
  'jsdoc/require-returns': 'off'
  'jsdoc/require-throws': 'error'
  'jsdoc/require-param': ['error', checkDestructured: false]
  'jsdoc/check-param-names': ['error', checkDestructured: false]
  'jsdoc/tag-lines': ['error', 'any', startLines: 1]
  'vitest/no-hooks': ['error', 'allow': ['afterEach']]
