root: true
settings:
  import/resolver:
    typescript: true
    node: true

ignorePatterns:
  - 'build'
  - 'vitest.config.ts'

plugins:
  - '@typescript-eslint'
  - 'prettier'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended-type-checked'
  - 'plugin:@typescript-eslint/stylistic-type-checked'
  - 'plugin:@typescript-eslint/strict-type-checked'
  - 'plugin:import/typescript'
  - 'plugin:prettier/recommended'
  - 'plugin:jsdoc/recommended-typescript-error'
  - 'plugin:vitest/legacy-all'
  - 'love'

rules:
  '@typescript-eslint/consistent-type-definitions': ['error', 'type']
  '@typescript-eslint/non-nullable-type-assertion-style': 'off'
  '@typescript-eslint/promise-function-async': 'off'
  '@typescript-eslint/strict-boolean-expressions': ['error', allowNullableObject: true]
  'import/no-default-export': 'error'
  'import/no-unresolved': 'error'
  'jsdoc/check-param-names': ['error', checkDestructured: false]
  'jsdoc/require-hyphen-before-param-description': 'error'
  'jsdoc/require-jsdoc': ['error', { 'require': { 'FunctionExpression': true, 'ArrowFunctionExpression': true } }]
  'jsdoc/require-param': ['error', checkDestructured: false]
  'jsdoc/require-returns': 'off'
  'jsdoc/require-throws': 'error'
  'jsdoc/tag-lines': ['error', 'any', startLines: 1]
  'vitest/no-hooks': ['error', 'allow': ['afterEach']]
