export * as airports from '~/airports/index.ts'
export * from '~/airports/types.ts'
export * as fares from '~/fares/index.ts'
export * from '~/fares/types.ts'
export * as flights from '~/flights/index.ts'
export * from '~/flights/types.ts'
