export { getActive } from '~/airports/getActive.ts'
export { getClosest } from '~/airports/getClosest.ts'
export { getDestinations } from '~/airports/getDestinations.ts'
export { getInfo } from '~/airports/getInfo.ts'
export { getRoutes } from '~/airports/getRoutes.ts'
