name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - name: determine dist-tag
        id: dist-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" =~ -([a-zA-Z]+) ]]; then
            echo "tag=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          fi
      - name: publish
        env:
          NPM_TAG: ${{ steps.dist-tag.outputs.tag }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm -r publish --provenance --access public --no-git-checks --tag "$NPM_TAG"
