name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  schedule:
    - cron: 0 20 * * *

jobs:
  test:
    name: test on ${{ matrix.os-release }}
    runs-on: ${{ matrix.os-release }}

    strategy:
      matrix:
        os-release:
          - blacksmith-4vcpu-ubuntu-2404
          - blacksmith-4vcpu-windows-2025

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run -r test

  coverage:
    name: collect coverage
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run -r test:unit
      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit

      - run: rm -rf coverage

      - run: pnpm run -r test:integration
      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration
