name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  schedule:
    - cron: 0 20 * * *

jobs:
  test:
    name: test on ${{ matrix.os-release }}
    runs-on: ${{ matrix.os-release }}

    strategy:
      matrix:
        os-release:
          - blacksmith-4vcpu-ubuntu-2404
          - blacksmith-4vcpu-windows-2025

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run -r test

  coverage:
    name: collect coverage
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run -r test:unit
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit

      - run: rm -rf coverage

      - run: pnpm run -r test:integration
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration
